spec-version: 0.36.0 # Avoid legacy behaviour of Hpack

name: crypton-socks
version: 0.6.2
synopsis: SOCKS Protocol Version 5
description: |
  A library implementing SOCKS Protocol Version 5.
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer:
- Mike Pilgrem <public@pilgrem.com>
- Kazu Yamamoto <kazu@iij.ad.jp>
category: Network
stability: experimental
github: mpilgrem/socks5
homepage: http://github.com/mpilgrem/socks5
extra-doc-files:
- CHANGELOG.md
- README.md

flags:
  example:
    description: Build the example application.
    manual: true
    default: false

  network-3-0-0-0:
    description: >-
      Use network-3.0.0.0 or later. If used the example application has a
      dependency on network-bsd.
    manual: false
    default: true

ghc-options:
- -Wall

dependencies:
- base >= 3 && < 5
- bytestring

library:
  source-dirs: src
  dependencies:
  - basement
  - cereal >= 0.3.1
  - network >= 2.6
  exposed-modules:
  - Network.Socks5
  - Network.Socks5.Lowlevel
  - Network.Socks5.Types

executables:
  crypton-socks-example:
    when:
    - condition: "!flag(example)"
      buildable: false
    - condition: flag(network-3-0-0-0)
      then:
        dependencies:
        - network >= 3.0.0.0
        - network-bsd
      else:
        dependencies:
        - network >= 2.6
    source-dirs: example
    main: Example.hs
    dependencies:
    - crypton-socks
