spec-version: 0.36.0 # Avoid legacy behaviour of Hpack

name: crypton-socks
version: 0.6.2
synopsis: Socks proxy (ver 5)
description: |
  Socks proxy (version 5) implementation.
copyright: Vincent Hanquez <vincent@snarc.org>
author: Vincent Hanquez <vincent@snarc.org>
maintainer:
- Mike Pilgrem <public@pilgrem.com>
- Kazu Yamamoto <kazu@iij.ad.jp>
category: Network
stability: experimental
github: mpilgrem/socks5
homepage: http://github.com/mpilgrem/socks5
extra-doc-files:
- CHANGELOG.md
- README.md
- Example.hs

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - base >= 3 && < 5
  - basement
  - bytestring
  - cereal >= 0.3.1
  - network >= 2.6
  exposed-modules:
  - Network.Socks5
  - Network.Socks5.Lowlevel
  - Network.Socks5.Types
